steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'us-west2-docker.pkg.dev/casestudy-2-370804/clumsy-image', 
           '.']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
           'us-west2-docker.pkg.dev/casestudy-2-370804/clumsy-image']
